import { useEffect, useState } from 'react';
import { listDockGuides, getGuide } from '../../../lib/platformcoreApi';

interface GuideSummary {
  guideId: string;
  entityId: string;
  entityName: string;
  status: string;
  score: number | null;
  schemaVersion: number | null;
  stale: boolean;
  metadata?: { portCode?: string };
  v4QaStatus?: string | null;
}

interface GuideDetail extends GuideSummary {
  sections: Record<string, Record<string, unknown>>;
  portAreaActivityDepth?: string | null;
  majorExperienceTransferTime?: string | null;
  returnComplexity?: string | null;
  returnDependencies?: string[] | null;
  impactAction?: string | null;
  generatedBy?: string | null;
  confidenceLevel?: string | null;
  contentUpdatedAt?: { seconds: number } | null;
  updatedAt?: { seconds: number };
}

function formatTs(ts: { seconds: number } | null | undefined) {
  if (!ts) return '—';
  return new Date(ts.seconds * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function SectionBlock({ name, data }: { name: string; data: Record<string, unknown> }) {
  const [open, setOpen] = useState(false);
  const keys = Object.keys(data);
  if (keys.length === 0) return null;
  return (
    <div className="section-block">
      <button className="section-block__toggle" onClick={() => setOpen(o => !o)}>
        <span className="section-block__name">{name}</span>
        <span className="section-block__count">{keys.length} field{keys.length !== 1 ? 's' : ''}</span>
        <span className="section-block__chevron">{open ? '▲' : '▼'}</span>
      </button>
      {open && (
        <div className="section-block__body">
          <table className="section-table">
            <tbody>
              {keys.map(k => (
                <tr key={k}>
                  <th>{k}</th>
                  <td>{renderValue(data[k])}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function renderValue(v: unknown): string {
  if (v === null || v === undefined) return '—';
  if (Array.isArray(v)) return v.join(', ');
  if (typeof v === 'object') return JSON.stringify(v, null, 2);
  return String(v);
}

function DetailView({ guide, onBack }: { guide: GuideDetail; onBack: () => void }) {
  const [rawOpen, setRawOpen] = useState(false);
  const portCode = guide.metadata?.portCode || '—';
  const sections = guide.sections || {};

  return (
    <div className="guide-detail">
      <button className="guide-detail__back" onClick={onBack}>← Back to list</button>

      <div className="guide-detail__header">
        <div>
          <span className="guide-detail__port">{portCode}</span>
          <h2 className="guide-detail__name">{guide.entityName}</h2>
          <span className="guide-detail__id">{guide.guideId}</span>
        </div>
        <div className="guide-detail__badges">
          <span className={`status-badge status-badge--${guide.status}`}>{guide.status}</span>
          {guide.stale && <span className="stale-badge">Stale</span>}
          {guide.schemaVersion && <span className="schema-badge">V{guide.schemaVersion}</span>}
        </div>
      </div>

      <div className="guide-detail__meta-row">
        <div className="meta-pill"><span>Score</span><strong>{guide.score ?? '—'}</strong></div>
        <div className="meta-pill"><span>Generated by</span><strong>{guide.generatedBy ?? '—'}</strong></div>
        <div className="meta-pill"><span>Confidence</span><strong>{guide.confidenceLevel ?? '—'}</strong></div>
        <div className="meta-pill"><span>Content updated</span><strong>{formatTs(guide.contentUpdatedAt)}</strong></div>
        <div className="meta-pill"><span>Last updated</span><strong>{formatTs(guide.updatedAt)}</strong></div>
      </div>

      {/* V4 badge row */}
      {(guide.portAreaActivityDepth || guide.majorExperienceTransferTime || guide.returnComplexity || guide.impactAction) && (
        <div className="guide-detail__v4">
          <div className="v4-row-label">V4 Intelligence</div>
          <div className="v4-row">
            {guide.portAreaActivityDepth    && <span className="v4-pill">{guide.portAreaActivityDepth}</span>}
            {guide.majorExperienceTransferTime && <span className="v4-pill">{guide.majorExperienceTransferTime}</span>}
            {guide.returnComplexity         && <span className="v4-pill">Return: {guide.returnComplexity}</span>}
          </div>
          {guide.impactAction && <p className="v4-impact">{guide.impactAction}</p>}
          {guide.returnDependencies?.length && (
            <ul className="v4-deps">
              {guide.returnDependencies.map((d, i) => <li key={i}>{d}</li>)}
            </ul>
          )}
        </div>
      )}

      {/* Sections */}
      <div className="guide-detail__sections">
        <h3 className="guide-detail__sections-title">Sections</h3>
        {Object.keys(sections).length === 0
          ? <p className="tab-empty">No section data.</p>
          : Object.entries(sections).map(([name, data]) => (
            <SectionBlock key={name} name={name} data={data as Record<string, unknown>} />
          ))
        }
      </div>

      {/* Raw JSON toggle */}
      <div className="guide-detail__raw">
        <button className="raw-toggle" onClick={() => setRawOpen(o => !o)}>
          {rawOpen ? 'Hide' : 'Show'} raw JSON
        </button>
        {rawOpen && (
          <pre className="raw-json">{JSON.stringify(guide, null, 2)}</pre>
        )}
      </div>
    </div>
  );
}

export default function PortGuidesTab() {
  const [guides, setGuides]       = useState<GuideSummary[]>([]);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState('');
  const [selected, setSelected]   = useState<GuideDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [search, setSearch]       = useState('');

  useEffect(() => {
    listDockGuides()
      .then((d: { guides: GuideSummary[] }) => setGuides(d.guides || []))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  async function openGuide(g: GuideSummary) {
    setDetailLoading(true);
    const entityId = g.entityId || g.guideId.replace(/^dock__/, '');
    try {
      const data = await getGuide('dock', entityId);
      setSelected(data.guide);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load guide');
    } finally {
      setDetailLoading(false);
    }
  }

  if (loading)       return <div className="tab-loading">Loading guides…</div>;
  if (error)         return <div className="tab-error">Error: {error}</div>;
  if (detailLoading) return <div className="tab-loading">Loading guide…</div>;
  if (selected)      return <DetailView guide={selected} onBack={() => setSelected(null)} />;

  const filtered = guides.filter(g =>
    !search ||
    g.entityName.toLowerCase().includes(search.toLowerCase()) ||
    (g.metadata?.portCode || '').toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="port-guides">
      <div className="port-guides__header">
        <h2 className="port-guides__title">Port Guides</h2>
        <input
          className="port-guides__search"
          placeholder="Search by name or port code…"
          value={search}
          onChange={e => setSearch(e.target.value)}
        />
      </div>

      <table className="queue-table">
        <thead>
          <tr>
            <th>Port</th>
            <th>Name</th>
            <th>Status</th>
            <th>Score</th>
            <th>Schema</th>
            <th>V4 QA</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {filtered.map(g => (
            <tr key={g.guideId}>
              <td><code>{g.metadata?.portCode || '—'}</code></td>
              <td>{g.entityName}</td>
              <td><span className={`status-badge status-badge--${g.status}`}>{g.status}</span></td>
              <td>{g.score ?? '—'}</td>
              <td>{g.schemaVersion ? `V${g.schemaVersion}` : '—'}</td>
              <td>
                {g.v4QaStatus
                  ? <span className={`v4-card__status v4-card__status--${g.v4QaStatus}`}>{g.v4QaStatus}</span>
                  : '—'}
              </td>
              <td>
                <button className="detail-btn" onClick={() => openGuide(g)}>View →</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
